### PR TITLE
not saving cache on exact key hit

### PR DESCRIPTION
**Pull request by royra**
Replicates the behavior of GitHub's cache action, and saves time on builds.

### CODE REVIEW

**Comment by jgoux** [comment]
I was going to open an issue about it, thanks for this @royra !

**Review by jackieli-tes — COMMENTED** [review]
Thanks for your contribution, can you resolve the conflicts and push?

**Comment by royra** [comment]
> Thanks for your contribution, can you resolve the conflicts and push?

@jackieli-tes done

**Review by jackieli-tes — APPROVED** [review]
Thanks for the contribution. LGTM

**Comment by jackieli-tes** [comment]
before merging, can you add a test for this?

**Comment by jackieli-tes** [comment]
Hmmm, you're right on this. The tests are all integration tests that's done using the actions. No unit test exists atm. And this one should be tested with unit test.

Will merge this. And defer the test situation.

**Pull request merged**
