### PR TITLE
feat: replace backend provider from MinIO to OpenDAL

### PR DESCRIPTION
**Pull request by everpcpc**
This PR replace the data access library with [OpenDAL](https://github.com/apache/incubator-opendal)

## Changes

- the access id/key are provided optional with environment variables now
- support other s3 authentication method with `aws-actions/configure-aws-credentials@v2`
- the cache key delimiter changed to `/` because of the limitation of OpenDAL: https://github.com/apache/incubator-opendal/issues/2073

## Fix Issues

- May fix: #24

### CODE REVIEW

**Comment by jackieli-tes** [comment]
Thanks for the PR, I'm for adding alternative back-end, but I don't feel adding backward incompatible change is beneficial. Can you what new feature would openDAL give us?

We should make this backward compatible unless there is very compelling reasons.

**Comment by everpcpc** [comment]
Hi @jackieli-tes, sorry for the late response.
The incompatible is due to OpenDAL only supporting delimiter `/` currently with scan operation.
We could make this backward compatible after https://github.com/apache/incubator-opendal/issues/2073 got resolved.

BTW, the new feature OpenDAL could give us is supporting various authentication method by AWS without access key. And also supporting various storage backends like GCS, Azure Blob, without changing any code.

**Comment by strophy** [comment]
[#2073](https://github.com/apache/incubator-opendal/issues/2073) got closed, this is now blocked by https://github.com/apache/incubator-opendal/issues/2762

**Comment by strophy** [comment]
https://github.com/apache/incubator-opendal/issues/2762 got closed, this is now tracked in https://github.com/apache/incubator-opendal/issues/3247

**Comment by Xuanwo** [comment]
Thanks for the long waiting. We fixed this issue now! We expect it to be released in v0.43.

**Comment by Xuanwo** [comment]
Hi, OpenDAL v0.44 has been released, and we can try again now!

**Comment by Sytten** [comment]
Did you guys test if the uncompress/compress is faster since the core is in rust?

**Comment by everpcpc** [comment]
@Sytten The uncompress/compress steps are not changed. Rust binding is only involved in upload/download steps.

**Comment by jackieli-tes** [comment]
rethinking about this. I think if you really want OpenDAL, this should really be a different plugin. The current s3 is working fine as is.

**Pull request closed without merging**
